forge "http://forge.puppetlabs.com"

mod "jenkins",        :git => 'git://github.com/jenkinsci/puppet-jenkins.git',  :ref => 'v1.1.0'
mod 'puppetlabs/apt', :git => 'git://github.com/puppetlabs/puppetlabs-apt.git', :ref => '1.4.0'
mod 'puppetlabs/ntp', :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git', :ref => '3.0.2'
mod 'saz/timezone',   :git => 'git://github.com/saz/puppet-timezone.git',       :ref => 'v3.0.1'
mod 'saz/locales',    :git => 'git://github.com/saz/puppet-locales.git',        :ref => 'v2.1.0'
mod 'mjhas/postfix',  :git => 'git://github.com/mjhas/postfix.git',             :ref => '0.0.5'
